openapi: 3.0.0
info:
  title: EnerzyFlow API
  description: API documentation for EnerzyFlow
  version: 1.0.0
servers:
  - url: http://localhost:5000
    description: Local server

paths:
  /:
    get:
      summary: Check if API is running
      responses:
        '200':
          description: API is running
          content:
            application/json:
              schema:
                type: string
                example: API is running

  /example:
    get:
      summary: Example endpoint
      responses:
        '200':
          description: Example response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Example endpoint response

  /profile:
    get:
      summary: Get user profile
      description: Retrieves the authenticated user's profile
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Successfully retrieved profile
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "123"
                  name:
                    type: string
                    example: "John Doe"
                  email:
                    type: string
                    example: "john@example.com"

    put:
      summary: Update user profile
      description: Updates the authenticated user's profile
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                businessName:
                  type: string
                  example: "Example Business"
                businessAddress:
                  type: string
                  example: "123 Example Street, Example City"
                city:
                  type: string
                  example: "Example City"
                state:
                  type: string
                  example: "Example State"
                pinCode:
                  type: string
                  example: "123456"
      responses:
        "200":
          description: Profile updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Profile updated successfully"
                  data:
                    type: object
                    properties:
                      businessName:
                        type: string
                        example: "Example Business"
                      businessAddress:
                        type: string
                        example: "123 Example Street, Example City"
                      city:
                        type: string
                        example: "Example City"
                      state:
                        type: string
                        example: "Example State"
                      pinCode:
                        type: string
                        example: "123456"

  /coins:
    get:
      summary: Get coins balance
      description: Retrieves the authenticated user's coins balance
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Successfully retrieved coins balance
          content:
            application/json:
              schema:
                type: object
                properties:
                  balance:
                    type: integer
                    example: 1000

  /refer:
    post:
      summary: Refer a friend
      description: Allows the authenticated user to refer a friend
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phoneNumber:
                  type: string
                  example: "+1234567890"
      responses:
        "200":
          description: Successfully referred a friend
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Referral invitation sent successfully"
                  data:
                    type: object
                    properties:
                      referrer:
                        type: string
                        example: "60d0fe4f5311236168a109ca"
                      phoneNumber:
                        type: string
                        example: "+1234567890"
                      status:
                        type: string
                        example: "pending"

  /referrals:
    get:
      summary: Get referral history
      description: Retrieves the authenticated user's referral history
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Successfully retrieved referral history
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "456"
                    phoneNumber:
                      type: string
                      example: "+1234567890"
                    status:
                      type: string
                      example: "Completed"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

# Add more paths and methods as needed